server:
  port: 8080

spring:
  application:
    name: acme-pedidos

acme:
  soap:
    endpoint: https://run.mocky.io/v3/19217075-6d4e-4818-98bc-416d1feb7b84

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
  api-docs:
    path: /v3/api-docs

logging:
  level:
    com.acme.pedidos: DEBUG
    org.springframework.web.reactive: INFO
